baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
name = 'MAURO'
siteDescription = "Questo è un sito HUGO di prova!!!"